#![allow(dead_code)]

use crate::common::{Counter, NodeId};
use serde::{Deserialize, Serialize};
use std::cmp::Ordering;
use std::collections::{HashMap, HashSet};

pub type CausalContext = HashMap<NodeId, Counter>;

/// A single causal event identifier: (node, counter).
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Dot {
    pub node_id: NodeId,
    pub counter: Counter,
}

impl Dot {
    pub fn new(node_id: NodeId, counter: Counter) -> Self {
        Self { node_id, counter }
    }
}

pub fn frontier_dvv(node_id: &NodeId, frontier: &HashMap<NodeId, Counter>) -> DotVersionVector {
    let counter = frontier.get(node_id).cloned().unwrap_or(0);

    DotVersionVector {
        dot: Dot::new(node_id.clone(), counter),
        context: frontier.clone(),
    }
}

pub fn vv_join(
    a: &HashMap<NodeId, Counter>,
    b: &HashMap<NodeId, Counter>,
) -> HashMap<NodeId, Counter> {
    let mut out = a.clone();
    for (k, v) in b {
        let e = out.entry(k.clone()).or_insert(0);
        *e = (*e).max(*v);
    }
    out
}

pub fn vv_meet(
    a: &HashMap<NodeId, Counter>,
    b: &HashMap<NodeId, Counter>,
) -> HashMap<NodeId, Counter> {
    let mut out = HashMap::new();
    let mut keys = HashSet::new();
    keys.extend(a.keys().cloned());
    keys.extend(b.keys().cloned());
    for k in keys {
        let a_val = a.get(&k).copied().unwrap_or(0);
        let b_val = b.get(&k).copied().unwrap_or(0);
        let m = a_val.min(b_val);
        if m > 0 {
            out.insert(k, m);
        }
    }
    out
}

pub fn vv_leq(a: &HashMap<NodeId, Counter>, b: &HashMap<NodeId, Counter>) -> bool {
    let mut keys = HashSet::new();
    keys.extend(a.keys().cloned());
    keys.extend(b.keys().cloned());
    keys.into_iter()
        .all(|k| a.get(&k).copied().unwrap_or(0) <= b.get(&k).copied().unwrap_or(0))
}

pub fn vv_lt(a: &HashMap<NodeId, Counter>, b: &HashMap<NodeId, Counter>) -> bool {
    vv_leq(a, b) && a != b
}

/// A true Dotted Version Vector (Almeida et al.)
///
/// The full causal knowledge of this DVV is:
///
///     effective(node) = context ∪ {dot}
///
/// * `dot`     
///
/// – the **latest event generated by this node**, stored
///   *outside* the context.  A counter of 0 means "no event
///   generated yet".
///
/// * `context`
///
/// – compact causal history of **all other observed events**.
///   It deliberately does **not** contain an entry for
///   `dot.node_id` at `dot.counter`.  It *may* contain an
///   older entry for `dot.node_id` that arrived via merge.
///
/// ### Invariant
///
/// `context[dot.node_id]` (defaulting to 0) is **strictly less than**
/// `dot.counter`, OR `dot.counter == 0` (no events yet).
///
/// This means the dot is always *outside* the context.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DotVersionVector {
    pub dot: Dot,
    pub context: CausalContext,
}

impl DotVersionVector {
    /// Create a fresh DVV for `node_id`.  Counter 0 = "no events yet".
    /// The context starts empty — we know nothing about any node.
    pub fn new(node_id: NodeId) -> Self {
        Self {
            dot: Dot::new(node_id, 0),
            context: CausalContext::new(),
        }
    }

    pub fn remove(&mut self, node_id: &NodeId) {
        self.context.remove(node_id);
    }
    // ── Effective knowledge ─────────────────────────────────────────

    /// The effective counter this DVV knows for `node_id`.
    ///
    ///   effective(n) = max(context[n], dot.counter if n == dot.node_id)
    ///
    /// This is the *only* correct way to ask "what do I know about node X?"
    pub fn effective_counter(&self, node_id: &NodeId) -> Counter {
        let counter = self.context.get(node_id).copied().unwrap_or(0);
        if *node_id == self.dot.node_id {
            counter.max(self.dot.counter)
        } else {
            counter
        }
    }

    /// Build the full effective version map (context ∪ {dot}).
    pub fn effective_map(&self) -> CausalContext {
        let mut map = self.context.clone();
        if self.dot.counter > 0 {
            let entry = map.entry(self.dot.node_id.clone()).or_insert(0);
            *entry = (*entry).max(self.dot.counter);
        }
        map
    }

    /// Does `self` causally dominate (or equal) `other`?
    ///
    /// ∀ node: effective_self(node) >= effective_other(node)
    pub fn descends(&self, other: &DotVersionVector) -> bool {
        let self_eff = self.effective_map();
        let other_eff = other.effective_map();

        let all_nodes: HashSet<_> = self_eff.keys().chain(other_eff.keys()).collect();
        for nid in all_nodes {
            let s = self_eff.get(nid).copied().unwrap_or(0);
            let o = other_eff.get(nid).copied().unwrap_or(0);
            if s < o {
                return false;
            }
        }
        true
    }

    /// Does `self`'s effective knowledge dominate a single dot?
    pub fn dominates_dot(&self, dot: &Dot) -> bool {
        self.effective_counter(&dot.node_id) >= dot.counter
    }

    /// True when the two DVVs are causally concurrent (incomparable).
    pub fn is_concurrent_with(&self, other: &DotVersionVector) -> bool {
        self.partial_cmp(other).is_none()
    }

    /// Record a new local event.
    ///
    /// 1. Retire the *current* dot into the context (if counter > 0).
    /// 2. Advance the dot counter.
    ///
    /// After this call the old dot lives in context and the new dot
    /// is strictly above it.
    pub fn event(&mut self) {
        if self.dot.counter > 0 {
            let entry = self.context.entry(self.dot.node_id.clone()).or_insert(0);
            *entry = (*entry).max(self.dot.counter);
        }
        self.dot.counter += 1;
    }

    /// Merge remote causal knowledge into this DVV (anti-entropy / sync).
    ///
    /// For **remote nodes** (node_id ≠ self.dot.node_id):
    ///   context[node_id] = max(context[node_id], remote_effective[node_id])
    ///
    /// For **our own node_id** the remote may have observed some of our
    /// past events (via transitive gossip).  We absorb that knowledge
    /// into context but **capped at dot.counter - 1** — the dot must
    /// stay outside the context.  We never inflate our own dot during
    /// merge because merge is *not* an event.
    ///
    /// The only exception is state-transfer / rejoin: if the remote
    /// somehow knows a higher counter for us than our own dot, we
    /// fast-forward the dot so that the invariant holds and no
    /// information is lost.
    pub fn merge(&mut self, other: &DotVersionVector) {
        let other_eff = other.effective_map();

        for (nid, &remote_counter) in &other_eff {
            if *nid == self.dot.node_id {
                if remote_counter < self.dot.counter {
                    // Remote knows about some of our past — absorb
                    // into context, but never up to our dot.
                    let entry = self.context.entry(nid.clone()).or_insert(0);
                    *entry = (*entry).max(remote_counter);
                } else if remote_counter > self.dot.counter {
                    // State-transfer / rejoin: remote knows more
                    // about us than we do.  Fast-forward.
                    // Context absorbs up to remote_counter - 1,
                    // dot becomes remote_counter.
                    let entry = self.context.entry(nid.clone()).or_insert(0);
                    *entry = (*entry).max(remote_counter - 1);
                    self.dot.counter = remote_counter;
                }
                // remote_counter == self.dot.counter → nothing to do.
                // Context already has at most dot.counter - 1, and
                // the dot itself is not stored in context.
            } else {
                let entry = self.context.entry(nid.clone()).or_insert(0);
                *entry = (*entry).max(remote_counter);
            }
        }
    }

    /// Produce a minimal delta for a peer whose knowledge is
    /// `remote_knowledge`.  The delta is a DVV that can be merged
    /// with the normal `merge` function.
    pub fn delta_since(&self, remote_knowledge: &CausalContext) -> DotVersionVector {
        let eff = self.effective_map();
        let mut delta_ctx = CausalContext::new();

        for (nid, &counter) in &eff {
            let known = remote_knowledge.get(nid).copied().unwrap_or(0);
            if counter > known && *nid != self.dot.node_id {
                delta_ctx.insert(nid.clone(), counter);
            }
        }

        let remote_knows_us = remote_knowledge
            .get(&self.dot.node_id)
            .copied()
            .unwrap_or(0);

        let dot_counter = if self.dot.counter > remote_knows_us {
            self.dot.counter
        } else {
            0
        };

        DotVersionVector {
            dot: Dot::new(self.dot.node_id.clone(), dot_counter),
            context: delta_ctx,
        }
    }

    /// Produce a "full-state" delta (useful for brand-new joiners).
    pub fn full_delta(&self) -> DotVersionVector {
        self.clone()
    }
}

/// Causality ordering on the **effective** version map (context ∪ {dot}).
impl PartialOrd for DotVersionVector {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        let self_eff = self.effective_map();
        let other_eff = other.effective_map();

        let all_nodes: HashSet<_> = self_eff.keys().chain(other_eff.keys()).collect();

        let mut has_less = false;
        let mut has_greater = false;

        for nid in all_nodes {
            let s = self_eff.get(nid).copied().unwrap_or(0);
            let o = other_eff.get(nid).copied().unwrap_or(0);
            match s.cmp(&o) {
                Ordering::Less => has_less = true,
                Ordering::Greater => has_greater = true,
                Ordering::Equal => {}
            }
        }

        match (has_less, has_greater) {
            (false, false) => Some(Ordering::Equal),
            (true, false) => Some(Ordering::Less),
            (false, true) => Some(Ordering::Greater),
            (true, true) => None,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nid(s: &str) -> NodeId {
        s.to_string()
    }

    fn create_dvv_with_counter(node: &str, counter: u64) -> DotVersionVector {
        let mut dvv = DotVersionVector::new(nid(node));
        for _ in 0..counter {
            dvv.event();
        }
        dvv
    }

    fn assert_dot_outside_context(dvv: &DotVersionVector) {
        if dvv.dot.counter == 0 {
            return; // no events yet, trivially satisfied
        }
        let ctx_val = dvv.context.get(&dvv.dot.node_id).copied().unwrap_or(0);
        assert!(
            ctx_val < dvv.dot.counter,
            "INVARIANT VIOLATED on node {}: context[{}] = {} but dot.counter = {}",
            dvv.dot.node_id,
            dvv.dot.node_id,
            ctx_val,
            dvv.dot.counter
        );
    }

    #[test]
    fn new_dvv_has_zero_counter_and_empty_context() {
        let dvv = DotVersionVector::new(nid("A"));
        assert_eq!(dvv.dot.counter, 0);
        assert_eq!(dvv.dot.node_id, "A");
        assert!(dvv.context.is_empty());
    }

    #[test]
    fn effective_counter_of_new_dvv_is_zero() {
        let dvv = DotVersionVector::new(nid("A"));
        assert_eq!(dvv.effective_counter(&nid("A")), 0);
        assert_eq!(dvv.effective_counter(&nid("B")), 0);
    }

    // LOCAL EVENTS

    #[test]
    fn single_event() {
        let mut dvv = DotVersionVector::new(nid("A"));
        dvv.event();
        assert_eq!(dvv.dot.counter, 1);
        assert_eq!(dvv.effective_counter(&nid("A")), 1);
        assert_dot_outside_context(&dvv);
    }

    #[test]
    fn multiple_events_monotonic() {
        let mut dvv = DotVersionVector::new(nid("A"));
        for i in 1..=10 {
            dvv.event();
            assert_eq!(dvv.dot.counter, i);
            assert_eq!(dvv.effective_counter(&nid("A")), i);
            assert_dot_outside_context(&dvv);
        }
    }

    #[test]
    fn event_retires_previous_dot_into_context() {
        let mut dvv = DotVersionVector::new(nid("A"));
        dvv.event(); // dot=1, context empty
        dvv.event(); // dot=2, context={A:1}
        assert_eq!(dvv.dot.counter, 2);
        assert_eq!(dvv.context.get(&nid("A")).copied().unwrap_or(0), 1);
        dvv.event(); // dot=3, context={A:2}
        assert_eq!(dvv.dot.counter, 3);
        assert_eq!(dvv.context.get(&nid("A")).copied().unwrap_or(0), 2);
    }

    #[test]
    fn event_does_not_affect_other_nodes() {
        let mut dvv = DotVersionVector::new(nid("A"));
        dvv.event();
        assert_eq!(dvv.effective_counter(&nid("B")), 0);
    }

    // INVARIANT CHECKS

    #[test]
    fn invariant_new() {
        let dvv = DotVersionVector::new(nid("A"));
        assert_eq!(dvv.dot.counter, 0);
        assert!(dvv.context.is_empty());
    }

    #[test]
    fn invariant_after_events() {
        for n in 1..=10 {
            let dvv = create_dvv_with_counter("A", n);
            assert_dot_outside_context(&dvv);
        }
    }

    #[test]
    fn invariant_after_merge() {
        let mut a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 5);
        a.merge(&b);
        assert_dot_outside_context(&a);
    }

    #[test]
    fn invariant_after_merge_then_event() {
        let mut a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 5);
        a.merge(&b);
        a.event();
        assert_dot_outside_context(&a);
    }

    #[test]
    fn invariant_complex_scenario() {
        let mut a = create_dvv_with_counter("A", 2);
        let mut b = create_dvv_with_counter("B", 3);
        let c = create_dvv_with_counter("C", 1);

        a.merge(&b);
        a.merge(&c);
        a.event();
        b.merge(&a);
        b.event();

        assert_dot_outside_context(&a);
        assert_dot_outside_context(&b);
    }

    // EFFECTIVE COUNTER vs CONTEXT

    #[test]
    fn effective_counter_combines_dot_and_context() {
        let dvv = create_dvv_with_counter("A", 3);
        // dot=3, context={A:2}
        assert_eq!(dvv.effective_counter(&nid("A")), 3);
        assert_eq!(dvv.context.get(&nid("A")).copied().unwrap_or(0), 2);
    }

    #[test]
    fn effective_counter_for_remote_uses_context_only() {
        let mut a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 5);
        a.merge(&b);
        assert_eq!(a.effective_counter(&nid("B")), 5);
        assert_eq!(a.context.get(&nid("B")).copied().unwrap_or(0), 5);
    }

    #[test]
    fn effective_map_includes_dot_and_context() {
        let mut a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 2);
        a.merge(&b);

        let eff = a.effective_map();
        assert_eq!(eff[&nid("A")], 3);
        assert_eq!(eff[&nid("B")], 2);
    }

    #[test]
    fn effective_map_excludes_zero_dot() {
        let a = DotVersionVector::new(nid("A"));
        let eff = a.effective_map();
        // dot.counter == 0, so own node should not appear in effective map
        assert!(!eff.contains_key(&nid("A")));
    }

    // MERGE / SYNC — PROPERTIES

    #[test]
    fn merge_acquires_new_nodes() {
        let mut a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 3);
        a.merge(&b);
        assert_eq!(a.effective_counter(&nid("B")), 3);
        assert_dot_outside_context(&a);
    }

    #[test]
    fn merge_takes_pointwise_maximum() {
        let mut a = create_dvv_with_counter("A", 5);
        let mut b = DotVersionVector::new(nid("B"));
        b.context.insert(nid("A"), 2);
        a.merge(&b);
        assert_eq!(a.effective_counter(&nid("A")), 5);
        assert_dot_outside_context(&a);
    }

    #[test]
    fn merge_does_not_decrease_counters() {
        let mut a = create_dvv_with_counter("A", 5);
        let b = DotVersionVector::new(nid("B"));
        let before = a.effective_counter(&nid("A"));
        a.merge(&b);
        assert!(a.effective_counter(&nid("A")) >= before);
    }

    #[test]
    fn merge_is_commutative_on_effective_knowledge() {
        let a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 2);

        let mut a1 = a.clone();
        let mut b1 = b.clone();

        a1.merge(&b);
        b1.merge(&a);

        for n in &[nid("A"), nid("B")] {
            assert_eq!(a1.effective_counter(n), b1.effective_counter(n));
        }
    }

    #[test]
    fn merge_is_idempotent() {
        let mut a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 2);
        a.merge(&b);
        let snapshot = a.effective_map();
        a.merge(&b);
        assert_eq!(a.effective_map(), snapshot);
    }

    #[test]
    fn merge_is_associative_on_effective_knowledge() {
        let a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 2);
        let c = create_dvv_with_counter("C", 4);

        let mut ab_c = a.clone();
        ab_c.merge(&b);
        ab_c.merge(&c);

        let mut bc = b.clone();
        bc.merge(&c);
        let mut a_bc = a.clone();
        a_bc.merge(&bc);

        for n in &[nid("A"), nid("B"), nid("C")] {
            assert_eq!(ab_c.effective_counter(n), a_bc.effective_counter(n));
        }
    }

    #[test]
    fn merge_self_does_not_change_effective_knowledge() {
        let a = create_dvv_with_counter("A", 3);
        let before = a.effective_map();
        let mut a2 = a.clone();
        a2.merge(&a);
        assert_eq!(a2.effective_map(), before);
        assert_dot_outside_context(&a2);
    }

    #[test]
    fn merge_does_not_create_events() {
        let a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("B", 5);
        let eff_before = a.effective_counter(&nid("A"));
        let mut a2 = a.clone();
        a2.merge(&b);
        assert_eq!(a2.effective_counter(&nid("A")), eff_before);
    }

    #[test]
    fn merge_three_nodes_full_sync() {
        let mut a = create_dvv_with_counter("A", 2);
        let mut b = create_dvv_with_counter("B", 3);
        let mut c = create_dvv_with_counter("C", 1);

        let a_snap = a.clone();
        let b_snap = b.clone();
        let c_snap = c.clone();

        a.merge(&b_snap);
        a.merge(&c_snap);
        b.merge(&a_snap);
        b.merge(&c_snap);
        c.merge(&a_snap);
        c.merge(&b_snap);

        for n in &[nid("A"), nid("B"), nid("C")] {
            assert_eq!(a.effective_counter(n), b.effective_counter(n));
            assert_eq!(b.effective_counter(n), c.effective_counter(n));
        }
    }

    #[test]
    fn merge_remote_knows_more_about_us() {
        let mut a = create_dvv_with_counter("A", 3);
        let mut b = DotVersionVector::new(nid("B"));
        b.context.insert(nid("A"), 10);

        a.merge(&b);
        assert_dot_outside_context(&a);
        assert_eq!(a.effective_counter(&nid("A")), 10);
    }

    // PARTIAL ORDER / CAUSALITY

    #[test]
    fn equal_dvvs_are_equal() {
        let a = create_dvv_with_counter("A", 3);
        let b = a.clone();
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Equal));
    }

    #[test]
    fn fresh_dvvs_different_nodes_are_equal() {
        let a = DotVersionVector::new(nid("A"));
        let b = DotVersionVector::new(nid("B"));
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Equal));
    }

    #[test]
    fn more_events_is_greater_same_node() {
        let a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("A", 5);
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Less));
        assert_eq!(b.partial_cmp(&a), Some(Ordering::Greater));
    }

    #[test]
    fn independent_nodes_with_events_are_concurrent() {
        let a = create_dvv_with_counter("A", 1);
        let b = create_dvv_with_counter("B", 1);
        assert!(a.is_concurrent_with(&b));
    }

    #[test]
    fn after_merge_and_event_is_greater() {
        let a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 3);
        let mut c = a.clone();
        c.merge(&b);
        c.event();

        assert_eq!(c.partial_cmp(&a), Some(Ordering::Greater));
        assert_eq!(c.partial_cmp(&b), Some(Ordering::Greater));
    }

    #[test]
    fn concurrent_after_independent_events() {
        let mut a = create_dvv_with_counter("A", 1);
        let mut b = create_dvv_with_counter("B", 1);

        let a_snap = a.clone();
        a.merge(&b);
        b.merge(&a_snap);

        a.event();
        b.event();

        assert!(a.is_concurrent_with(&b));
    }

    #[test]
    fn partial_order_after_one_sided_sync() {
        let mut a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 1);
        a.merge(&b);
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Greater));
        assert_eq!(b.partial_cmp(&a), Some(Ordering::Less));
    }

    #[test]
    fn concurrent_three_way() {
        let a = create_dvv_with_counter("A", 1);
        let b = create_dvv_with_counter("B", 1);
        let c = create_dvv_with_counter("C", 1);
        assert!(a.is_concurrent_with(&b));
        assert!(b.is_concurrent_with(&c));
        assert!(a.is_concurrent_with(&c));
    }

    #[test]
    fn partial_cmp_with_unknown_nodes() {
        let a = create_dvv_with_counter("A", 5);
        let b = DotVersionVector::new(nid("B"));
        // A effective: {A:5}.  B effective: {} (empty).
        // Only key is A: 5 vs 0 → A > B
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Greater));
        assert_eq!(b.partial_cmp(&a), Some(Ordering::Less));
    }

    #[test]
    fn partial_ord_antisymmetry() {
        let a = create_dvv_with_counter("A", 3);
        let b = create_dvv_with_counter("A", 5);
        assert_eq!(a.partial_cmp(&b), Some(Ordering::Less));
        assert_eq!(b.partial_cmp(&a), Some(Ordering::Greater));
    }

    #[test]
    fn partial_ord_reflexive() {
        let a = create_dvv_with_counter("A", 7);
        assert_eq!(a.partial_cmp(&a), Some(Ordering::Equal));
    }

    #[test]
    fn causality_is_transitive() {
        let a = create_dvv_with_counter("A", 1);
        let mut b = a.clone();
        b.event();
        let mut c = b.clone();
        c.event();

        assert_eq!(a.partial_cmp(&b), Some(Ordering::Less));
        assert_eq!(b.partial_cmp(&c), Some(Ordering::Less));
        assert_eq!(a.partial_cmp(&c), Some(Ordering::Less));
    }

    // DESCENDS / DOMINATES

    #[test]
    fn descends_self() {
        let a = create_dvv_with_counter("A", 3);
        assert!(a.descends(&a));
    }

    #[test]
    fn descends_after_merge() {
        let mut a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 3);
        a.merge(&b);
        assert!(a.descends(&b));
        assert!(!b.descends(&a));
    }

    #[test]
    fn does_not_descend_concurrent() {
        let a = create_dvv_with_counter("A", 1);
        let b = create_dvv_with_counter("B", 1);
        assert!(!a.descends(&b));
        assert!(!b.descends(&a));
    }

    #[test]
    fn dominates_dot_after_event() {
        let a = create_dvv_with_counter("A", 3);
        assert!(a.dominates_dot(&Dot::new(nid("A"), 2)));
        assert!(a.dominates_dot(&Dot::new(nid("A"), 3)));
    }

    #[test]
    fn does_not_dominate_future_dot() {
        let a = create_dvv_with_counter("A", 3);
        assert!(!a.dominates_dot(&Dot::new(nid("A"), 4)));
    }

    #[test]
    fn dominates_remote_dot_after_merge() {
        let mut a = create_dvv_with_counter("A", 1);
        let b = create_dvv_with_counter("B", 5);
        a.merge(&b);
        assert!(a.dominates_dot(&Dot::new(nid("B"), 3)));
        assert!(a.dominates_dot(&Dot::new(nid("B"), 5)));
        assert!(!a.dominates_dot(&Dot::new(nid("B"), 6)));
    }

    #[test]
    fn dominates_dot_counter_zero() {
        let a = DotVersionVector::new(nid("A"));
        assert!(a.dominates_dot(&Dot::new(nid("A"), 0)));
        assert!(a.dominates_dot(&Dot::new(nid("B"), 0)));
    }

    // DELTA GENERATION

    #[test]
    fn delta_since_empty_knowledge() {
        let a = create_dvv_with_counter("A", 3);
        let delta = a.delta_since(&CausalContext::new());
        assert_eq!(delta.dot.counter, 3);
    }

    #[test]
    fn delta_since_up_to_date() {
        let a = create_dvv_with_counter("A", 3);
        let mut remote = CausalContext::new();
        remote.insert(nid("A"), 3);
        let delta = a.delta_since(&remote);
        assert_eq!(delta.dot.counter, 0);
    }

    #[test]
    fn delta_since_partial_knowledge() {
        let mut a = create_dvv_with_counter("A", 5);
        let b = create_dvv_with_counter("B", 3);
        a.merge(&b);

        let mut remote = CausalContext::new();
        remote.insert(nid("A"), 5);

        let delta = a.delta_since(&remote);
        assert_eq!(delta.effective_counter(&nid("B")), 3);
        assert_eq!(delta.dot.counter, 0); // remote knows our dot
    }

    #[test]
    fn delta_merge_brings_peer_up_to_date() {
        let mut a = create_dvv_with_counter("A", 4);
        let b = create_dvv_with_counter("B", 2);
        a.merge(&b);

        let mut c = DotVersionVector::new(nid("C"));
        let delta = a.delta_since(&c.effective_map());
        c.merge(&delta);

        assert_eq!(c.effective_counter(&nid("A")), 4);
        assert_eq!(c.effective_counter(&nid("B")), 2);
        assert_dot_outside_context(&c);
    }

    #[test]
    fn full_delta_is_clone() {
        let a = create_dvv_with_counter("A", 3);
        assert_eq!(a, a.full_delta());
    }

    #[test]
    fn accumulate_multiple_deltas() {
        let mut source = DotVersionVector::new(nid("S"));
        let mut sink = DotVersionVector::new(nid("T"));

        for batch in 0..5u64 {
            source.event();
            source.event();
            let delta = source.delta_since(&sink.effective_map());
            sink.merge(&delta);
            assert_eq!(sink.effective_counter(&nid("S")), (batch + 1) * 2,);
            assert_dot_outside_context(&sink);
        }
        assert_eq!(sink.effective_counter(&nid("S")), 10);
    }

    // DELTA CRDT ROUND-TRIP

    #[test]
    fn delta_crdt_protocol_round_trip() {
        let mut a = create_dvv_with_counter("A", 3);
        let mut b = create_dvv_with_counter("B", 2);

        a.merge(&b.full_delta());
        b.merge(&a.full_delta());

        a.event();
        a.event();

        let delta = a.delta_since(&b.effective_map());
        b.merge(&delta);

        assert_eq!(b.effective_counter(&nid("A")), 5);
        assert!(b.descends(&a));
        assert_dot_outside_context(&b);
    }

    // REPLICATED COUNTER SCENARIO

    #[test]
    fn replicated_counter_scenario() {
        let mut r1 = DotVersionVector::new(nid("R1"));
        let mut r2 = DotVersionVector::new(nid("R2"));
        let mut r3 = DotVersionVector::new(nid("R3"));

        r1.event();
        r1.event();
        r2.event();

        r2.merge(&r1);
        r2.event();
        r3.event();
        r3.merge(&r2);

        let total: Counter = [nid("R1"), nid("R2"), nid("R3")]
            .iter()
            .map(|n| r3.effective_counter(n))
            .sum();
        assert_eq!(total, 5);

        assert_dot_outside_context(&r1);
        assert_dot_outside_context(&r2);
        assert_dot_outside_context(&r3);
    }

    // NETWORK PARTITION & HEAL

    #[test]
    fn network_partition_and_heal() {
        let mut a = DotVersionVector::new(nid("A"));
        let mut b = DotVersionVector::new(nid("B"));

        a.event();
        b.event();
        let a_snap = a.clone();
        a.merge(&b);
        b.merge(&a_snap);

        // PARTITION
        a.event();
        a.event();
        b.event();
        b.event();
        b.event();

        assert!(a.is_concurrent_with(&b));

        // HEAL
        let a_snap = a.clone();
        a.merge(&b);
        b.merge(&a_snap);

        assert!(a.descends(&b));
        assert!(b.descends(&a));
        assert_dot_outside_context(&a);
        assert_dot_outside_context(&b);
    }

    // LATE JOINER

    #[test]
    fn late_joiner_catches_up() {
        let mut a = create_dvv_with_counter("A", 10);
        let b = create_dvv_with_counter("B", 7);
        a.merge(&b);

        let mut c = DotVersionVector::new(nid("C"));
        c.merge(&a.full_delta());

        assert_eq!(c.effective_counter(&nid("A")), 10);
        assert_eq!(c.effective_counter(&nid("B")), 7);
        assert_dot_outside_context(&c);
    }

    // CONFLICTING WRITES DETECTION

    #[test]
    fn conflicting_writes_detected() {
        let mut a = create_dvv_with_counter("A", 1);
        let mut b = create_dvv_with_counter("B", 1);

        let a_snap = a.clone();
        a.merge(&b);
        b.merge(&a_snap);

        a.event();
        b.event();

        assert!(a.is_concurrent_with(&b));
        assert!(!b.dominates_dot(&a.dot));
        assert!(!a.dominates_dot(&b.dot));

        let a_snap = a.clone();
        a.merge(&b);
        b.merge(&a_snap);

        assert!(a.descends(&b));
        assert!(b.descends(&a));
    }

    // DOT DOMINATION FOR DEDUP

    #[test]
    fn dot_domination_for_dedup() {
        let mut a = create_dvv_with_counter("A", 5);
        let b = create_dvv_with_counter("B", 3);
        a.merge(&b);

        assert!(a.dominates_dot(&Dot::new(nid("B"), 2)));
        assert!(a.dominates_dot(&Dot::new(nid("B"), 3)));
        assert!(!a.dominates_dot(&Dot::new(nid("B"), 4)));
    }

    // CHAIN OF GOSSIP

    #[test]
    fn chain_of_gossip() {
        let a = create_dvv_with_counter("A", 3);
        let mut b = DotVersionVector::new(nid("B"));
        b.merge(&a);
        b.event();

        let mut c = DotVersionVector::new(nid("C"));
        c.merge(&b);
        c.event();

        let mut d = DotVersionVector::new(nid("D"));
        d.merge(&c);
        d.event();

        assert_eq!(d.effective_counter(&nid("A")), 3);
        assert!(d.descends(&a));
        assert!(d.descends(&b));
        assert!(d.descends(&c));
        assert_dot_outside_context(&d);
    }

    // MERGE CONCURRENT → COMMON DESCENDANT

    #[test]
    fn merge_concurrent_creates_common_descendant() {
        let a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 3);
        assert!(a.is_concurrent_with(&b));

        let mut ma = a.clone();
        let mut mb = b.clone();
        ma.merge(&b);
        mb.merge(&a);

        assert!(ma.descends(&a));
        assert!(ma.descends(&b));
        assert!(mb.descends(&a));
        assert!(mb.descends(&b));
    }

    // DOT EQUALITY / HASH

    #[test]
    fn dot_equality() {
        assert_eq!(Dot::new(nid("A"), 3), Dot::new(nid("A"), 3));
        assert_ne!(Dot::new(nid("A"), 3), Dot::new(nid("A"), 4));
        assert_ne!(Dot::new(nid("A"), 3), Dot::new(nid("B"), 3));
    }

    #[test]
    fn dot_in_hashset() {
        let mut set = HashSet::new();
        set.insert(Dot::new(nid("A"), 1));
        set.insert(Dot::new(nid("A"), 1));
        set.insert(Dot::new(nid("A"), 2));
        assert_eq!(set.len(), 2);
    }

    // CLONE INDEPENDENCE

    #[test]
    fn clone_is_independent() {
        let mut a = create_dvv_with_counter("A", 3);
        let b = a.clone();
        a.event();
        assert_eq!(b.dot.counter, 3);
        assert_eq!(a.dot.counter, 4);
    }

    // FIVE-NODE CLUSTER

    #[test]
    fn five_node_cluster_full_replication() {
        let names: Vec<String> = (0..5).map(|i| format!("N{}", i)).collect();
        let mut dvvs: Vec<DotVersionVector> = names
            .iter()
            .map(|n| DotVersionVector::new(n.clone()))
            .collect();

        for (i, dvv) in dvvs.iter_mut().enumerate() {
            for _ in 0..(i + 1) {
                dvv.event();
            }
        }

        // Full pairwise sync — take snapshots FIRST, then merge
        let snaps: Vec<_> = dvvs.iter().cloned().collect();
        for dvv in dvvs.iter_mut() {
            for snap in &snaps {
                dvv.merge(snap);
            }
        }

        // All should agree on effective counters
        for i in 1..5 {
            for j in 0..5 {
                assert_eq!(
                    dvvs[i].effective_counter(&names[j]),
                    dvvs[0].effective_counter(&names[j]),
                    "Node {} and Node 0 disagree on {}",
                    i,
                    names[j]
                );
            }
            assert_dot_outside_context(&dvvs[i]);
        }

        // Verify actual values: N0=1, N1=2, N2=3, N3=4, N4=5
        for i in 0..5 {
            assert_eq!(dvvs[0].effective_counter(&names[i]), (i + 1) as Counter,);
        }
    }

    // RAPID INTERLEAVED EVENTS & SYNC

    #[test]
    fn rapid_event_sync_interleave() {
        let mut a = DotVersionVector::new(nid("A"));
        let mut b = DotVersionVector::new(nid("B"));

        for round in 1..=20 {
            a.event();
            b.event();

            if round % 5 == 0 {
                a.merge(&b);
                b.merge(&a);
            }
        }

        a.merge(&b);
        b.merge(&a);

        assert_eq!(a.effective_counter(&nid("A")), 20);
        assert_eq!(a.effective_counter(&nid("B")), 20);
        assert_eq!(b.effective_counter(&nid("A")), 20);
        assert_eq!(b.effective_counter(&nid("B")), 20);

        assert_dot_outside_context(&a);
        assert_dot_outside_context(&b);
    }

    // EDGE: MERGE TWO FRESH DVVs

    #[test]
    fn merge_two_fresh_dvvs() {
        let mut a = DotVersionVector::new(nid("A"));
        let b = DotVersionVector::new(nid("B"));
        a.merge(&b);
        assert_eq!(a.effective_counter(&nid("A")), 0);
        assert_eq!(a.effective_counter(&nid("B")), 0);
        // dot should remain at 0 — no phantom event
        assert_eq!(a.dot.counter, 0);
    }

    // EDGE: EFFECTIVE COUNTER UNKNOWN NODE

    #[test]
    fn effective_counter_unknown_returns_zero() {
        let a = DotVersionVector::new(nid("A"));
        assert_eq!(a.effective_counter(&nid("UNKNOWN")), 0);
    }

    // EVENT AFTER MERGE PRESERVES REMOTE KNOWLEDGE

    #[test]
    fn event_after_merge_preserves_remote_knowledge() {
        let mut a = create_dvv_with_counter("A", 2);
        let b = create_dvv_with_counter("B", 4);
        a.merge(&b);

        let b_before = a.effective_counter(&nid("B"));
        a.event();
        assert_eq!(a.effective_counter(&nid("B")), b_before);
        assert_dot_outside_context(&a);
    }

    // STATE TRANSFER / REJOIN

    #[test]
    fn state_transfer_fast_forward() {
        // A was at 3, but a remote (via transitive gossip) learned
        // A went up to 10.  When A merges that info it must
        // fast-forward without losing the invariant.
        let mut a = create_dvv_with_counter("A", 3);
        let mut remote = DotVersionVector::new(nid("B"));
        remote.context.insert(nid("A"), 10);

        a.merge(&remote);
        assert_dot_outside_context(&a);
        assert_eq!(a.effective_counter(&nid("A")), 10);

        // A can still generate events beyond the fast-forward
        a.event();
        assert_eq!(a.effective_counter(&nid("A")), 11);
        assert_dot_outside_context(&a);
    }

    // SYMMETRY: MUTUAL FULL SYNC = EQUAL

    #[test]
    fn mutual_full_sync_yields_equal_effective_maps() {
        let mut a = create_dvv_with_counter("A", 4);
        let mut b = create_dvv_with_counter("B", 7);
        let c = create_dvv_with_counter("C", 2);

        a.merge(&c);
        b.merge(&c);

        let a_snap = a.clone();
        let b_snap = b.clone();
        a.merge(&b_snap);
        b.merge(&a_snap);

        // Effective maps must agree after mutual sync
        for n in &[nid("A"), nid("B"), nid("C")] {
            assert_eq!(a.effective_counter(n), b.effective_counter(n));
        }
    }

    #[test]
    fn vv_lt_strict_progress() {
        let mut prev = HashMap::new();
        prev.insert("A".to_string(), 2);
        let mut next = HashMap::new();
        next.insert("A".to_string(), 2);
        next.insert("B".to_string(), 1);
        assert!(vv_lt(&prev, &next));
    }

    #[test]
    fn vv_lt_rejects_no_progress() {
        let mut prev = HashMap::new();
        prev.insert("A".to_string(), 2);
        let mut next = HashMap::new();
        next.insert("A".to_string(), 2);
        assert!(!vv_lt(&prev, &next));
    }
}
