// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Envelope {
    #[prost(oneof = "envelope::Payload", tags = "1, 2, 3, 4, 5")]
    pub payload: ::core::option::Option<envelope::Payload>,
}
/// Nested message and enum types in `Envelope`.
pub mod envelope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "1")]
        Handshake(super::Handshake),
        #[prost(message, tag = "2")]
        Heartbeat(super::Heartbeat),
        #[prost(message, tag = "3")]
        HeartbeatAck(super::HeartbeatAck),
        #[prost(message, tag = "4")]
        CrdtOp(super::CrdtOp),
        #[prost(message, tag = "5")]
        EpochAnnounce(super::EpochAnnounce),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Handshake {
    /// Globally unique node identifier (UUID recommended).
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    /// Human-readable name (optional).
    #[prost(string, tag = "2")]
    pub node_name: ::prost::alloc::string::String,
    /// Protocol version for forward-compat checks.
    #[prost(uint32, tag = "3")]
    pub version: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Heartbeat {
    /// Monotonic sequence number so the responder can detect gaps.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartbeatAck {
    /// Echoes the seq from the Heartbeat it is acknowledging.
    #[prost(uint64, tag = "1")]
    pub seq: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CrdtOp {
    /// Which CRDT instance this operation targets.
    #[prost(string, tag = "1")]
    pub crdt_id: ::prost::alloc::string::String,
    /// Opaque, serialised operation payload.  The CRDT layer will
    /// deserialise this according to the crdt_id's registered type.
    #[prost(bytes = "vec", tag = "2")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Hybrid-logical or Lamport timestamp for crdt ordering.
    #[prost(uint64, tag = "3")]
    pub hlc_ts: u64,
    /// Originating node so we can break ties / attribute ops.
    #[prost(string, tag = "4")]
    pub origin_node_id: ::prost::alloc::string::String,
    /// GC epoch when this operation was created (0 if not applicable).
    #[prost(uint64, tag = "5")]
    pub gc_epoch: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpochAnnounce {
    /// The current GC epoch of the sending node.
    #[prost(uint64, tag = "1")]
    pub epoch: u64,
    /// Node ID of the sender.
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
}
